[package]
name = "tensorrt-sys"
version = "0.1.0"
authors = ["Mason Stallmo <masonstallmo@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2.62"

[build-dependencies]
cmake = "0.1.41"