# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: mstallmo/tensorrt-rs:0.2
    steps:
      - checkout
      - run: cargo build --release
      - persist_to_workspace:
          root: /root
          paths:
            - project
  # Running tests are currently broken due to an -fPIC issue in docker. Could be related to the shared libs that are
  # installed by default in the nvidia container that we're using as a base.
  test-tensorrt-sys:
    docker:
      - image: mstallmo/tensorrt-rs:0.2
    steps:
      - attach_workspace:
          at: /root
      - run: cd tensorrt-sys && cargo test
# Orchestrate or schedule a set of jobs
workflows:
  build-docker:
    jobs:
      - build
      - test-tensorrt-sys:
          requires:
            - build