[package]
name = "tensorrt"
version = "0.1.1"
authors = ["Mason Stallmo <masonstallmo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Uncomment when working locally
tensorrt-sys = {version = "0.1", path="../tensorrt-sys"}

#tensorrt-sys = {version = "0.1.1", git="https://github.com/mstallmo/tensorrt-rs"}

[dev-dependencies]
lazy_static = "1.4.0"
